# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objects.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\robjects.proto\"c\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"f\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x17\n\x06status\x18\x03 \x01(\x0e\x32\x07.StatusB\x0b\n\titem_type*?\n\x05Genre\x12\x0b\n\x07MYSTERY\x10\x00\x12\x0b\n\x07\x46ICTION\x10\x01\x12\x0f\n\x0bNON_FICTION\x10\x02\x12\x0b\n\x07ROMANCE\x10\x03*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objects_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=222
  _GENRE._serialized_end=285
  _STATUS._serialized_start=287
  _STATUS._serialized_end=321
  _BOOK._serialized_start=17
  _BOOK._serialized_end=116
  _INVENTORYITEM._serialized_start=118
  _INVENTORYITEM._serialized_end=220
# @@protoc_insertion_point(module_scope)
